### ISSUE TITLE
Possible to hide password

### ISSUE THREAD

**Issue by SamVerschueren** [felipefdl/wercker-status#5]
Is it possible to hide the password and username if the token is created? It doesn't feel right to have it in plain text in the editor.

**Comment by felipefdl** [comment]
@SamVerschueren Sure, I agree. But I need store the password because the werker token is temporary. I gonna analyse this.

**Comment by SamVerschueren** [comment]
Ah oke, didn't knew it was temporary. If I find the time I will also have a look into this.

**Comment by IyadAssaf** [comment]
Just to chime in on this, I too am not terribly comfortable having my password in plaintext in the settings but I would be happy enough with the password field just having hidden characters.

Looking through the atom docs and forums, it looks like these guys have a good solution to get this working since atom doesn't allow you to set the input type for passwords - https://discuss.atom.io/t/password-fields-when-using-editorview-subview/11061/5 

I'm happy to make a pull req at some point if you'd like.

**Comment by felipefdl** [comment]
Nice @IyadAssaf ! I will be happy accept your pull request.
